### ISSUE TITLE
MacOS下安装失败Vundle.vim插件失败

### ISSUE THREAD

**Issue by easyli** [feix760/yuan#1]
安装Vundle.vim失败,日志显示https://github.com/gmarik/Vundle.vim 不存在

通过如下方式在Mac下安装成功。

```bash
rm -rf ~/.vim/bundle/Vundle.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# then open vim
:PluginInstall
```

**Comment by feix760** [comment]
git clone成功了么？

**Comment by easyli** [comment]
安装步骤如下:

1. git clone --recursive https://github.com/feix760/yuan.git temp
2. cp -r .vim ~/
3. cp .vimrc ~/
4. 打开 vim
5. 输入:PluginInstall

之后显示安装过程, Vundle.vim 有感叹号, 其它插件前都是 对号

iMac 和 rmbp 都安装失败。忘记截图, 抱歉

按照我上面的方法, 单独重新装 Vundle 就可以了

**Comment by feix760** [comment]
感叹号是需要更新的意思，能够运行`:PluginInstall`就说明Vundle安装成功了

**Comment by easyli** [comment]
安装
![image](https://cloud.githubusercontent.com/assets/3353944/24575018/5610b160-16ce-11e7-9cec-6e165af236ca.png)

按L键查看的警告提示

![image](https://cloud.githubusercontent.com/assets/3353944/24575045/d6145c5e-16ce-11e7-9f06-6c6017c07aa5.png)

Vundle管理的插件是可以用的

![image](https://cloud.githubusercontent.com/assets/3353944/24575071/1abf274e-16cf-11e7-9a76-f8506464cf1b.png)

**Comment by feix760** [comment]
感谢 @easyli 的反馈，我现在把这个关了
